name: golang-docker-ci

on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: self-hosted
    steps:
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/setup-qemu-action@v1.2.0
      - uses: docker/build-push-action@v2.10.0
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}