name: golang-docker-ci

on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out